# Generated by Django 6.0.6 on 2026-06-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=200)),
                ('service', models.CharField(choices=[('External Audit', 'External Audit'), ('Internal Audit', 'Internal Audit'), ('Project Audit', 'Project Audit'), ('Tax Advisory', 'Tax Advisory'), ('Tax Return Filing', 'Tax Return Filing'), ('Accounting Services', 'Accounting Services'), ('Financial Advisory', 'Financial Advisory'), ('Training & Capacity Building', 'Training & Capacity Building')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
