# Generated by Django 6.0.6 on 2026-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='service_area',
            field=models.CharField(blank=True, choices=[('Audit & Assurance', 'Audit & Assurance'), ('Tax Advisory & Compliance', 'Tax Advisory & Compliance'), ('Tax Objections & Appeals', 'Tax Objections & Appeals'), ('Capacity Building & Training', 'Capacity Building & Training')], default='', max_length=100),
        ),
    ]
