# Generated by Django 6.0.6 on 2026-07-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inquiry_service_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='programme',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
