# Generated by Django 6.0.6 on 2026-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inquiry_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Bootstrap Icons class, e.g. 'bi bi-people-fill'", max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Training Audience',
                'verbose_name_plural': 'Training Audiences',
                'ordering': ['order', 'label'],
            },
        ),
    ]
