# Generated by Django 6.0.6 on 2026-07-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_training_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='email_sent',
            field=models.BooleanField(default=True, help_text='False if the notification email failed to send.'),
        ),
    ]
