# Generated by Django 6.0.6 on 2026-09-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('', '— No preference —'), ('Morning (9:00 AM – 12:00 PM)', 'Morning (9:00 AM – 12:00 PM)'), ('Early Afternoon (12:00 PM – 2:00 PM)', 'Early Afternoon (12:00 PM – 2:00 PM)'), ('Late Afternoon (2:00 PM – 5:00 PM)', 'Late Afternoon (2:00 PM – 5:00 PM)')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='wants_booking',
            field=models.BooleanField(default=False, verbose_name='This is a consultation booking request'),
        ),
    ]
