# Generated by Django 6.0.6 on 2026-09-26 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_inquiry_booking_status_inquiry_preferred_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto-generate from the title.', max_length=250, unique=True)),
                ('excerpt', models.CharField(blank=True, default='', help_text='A short summary shown on the News list page. Leave blank to auto-generate from the start of the article.', max_length=300)),
                ('body', models.TextField(help_text='Write the article in plain paragraphs. Leave a blank line between paragraphs — no HTML or code needed.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('category', models.CharField(blank=True, default='', help_text="Optional, e.g. 'Tax Advisory'. Shown as a small label on the article.", max_length=100)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to save as a draft — it will not appear on the website until this is checked.')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
