# Generated by Django 6.0.6 on 2026-09-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='flagged_as_likely_spam',
            field=models.BooleanField(default=False, help_text='Automatically flagged because the message contained a link. Not necessarily spam — please review before acting.'),
        ),
    ]
