# Generated by Django 6.0.6 on 2026-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Building Stronger Organisations', help_text='Main heading shown in the intro section of the Training page.', max_length=200)),
                ('lead', models.TextField(default='At Obusubiri & Associates, we provide practical, results-oriented training programs designed to strengthen governance, financial management, compliance, accountability and organisational performance.', help_text='Lead paragraph shown below the heading.')),
                ('pullquote', models.TextField(default='Our programs are tailored for NGOs, Development Partners, Government Institutions, Faith-Based Organisations, Educational Institutions, SACCOs and Private Sector Organisations.', help_text='Pull-quote (gold-bordered blockquote) shown below the lead.')),
            ],
            options={
                'verbose_name': 'Training page intro',
                'verbose_name_plural': 'Training page intro',
            },
        ),
    ]
